version: '3.8'
services:
  app:
    container_name: todo_app
    image: todo_app:latest
    restart: always
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - default
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=todo_db
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/data/postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=admin
      - POSTGRES_DB=todo_db
    networks:
      - default
    restart: always
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - '80:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    networks:
      - default
    restart: always
volumes:
  progresDB:
networks:
  default: